version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "el"
      POSTGRES_PASSWORD: "ozon"
      POSTGRES_DB: "db"
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: